apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: orders-api
  template:
    metadata:
      labels:
        app: orders-api
    spec:
      containers:
        - name: orders-api
          image: orderflow/orders-api:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: orders-api-config
          env:
            - name: ConnectionStrings__OrdersDb
              valueFrom:
                secretKeyRef:
                  name: orders-api-secrets
                  key: connection-string
            - name: RabbitMq__Password
              valueFrom:
                secretKeyRef:
                  name: orders-api-secrets
                  key: rabbitmq-password
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 3
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 3
